### ISSUE TITLE
Question / Remark : using ohif viewer with https://dicomcloud.azurewebsites.net/api loading status

### ISSUE THREAD

**Issue by sylvainb31** [DICOMcloud/DICOMcloud#103]
Hello @Zaid-Safadi 

I am contacting you because I have made tests on the ohif viewer displaying images from https://server.dcmjs.org and from your server https://dicomcloud.azurewebsites.net

I have noticed that pointing toward your server, the viewer loading status ("Loading ...") varies, whereas when pointing toward https://server.dcmjs.org it doesn't.

Do you know why ? Is it a difference in the metadata sent ? 

Thanks for your help 

Sylvain

**Comment by Zaid-Safadi** [comment]
Hi @sylvainb31 , will you please explain more the different behavior you are seeing between both? I am not following what the issue is with the loading status.
Also, are you using the same OHIF version on both and just switching backend servers or are these two different OHIF installations?

**Comment by sylvainb31** [comment]
Hi,

Sorry for not giving full details on the first post.

I am using the embedded viewer inside my asp net core application 3.1.

Viewer version : "library": "@ohif/viewer@4.5.2",

I am using the same OHIF version and just switching the servers.

Here is my configuration : 

```
window.OHIFViewer.installViewer(
        {
            routerBasename: '/Home/Viewer',
            extensions: [],
            showStudyList: true,
            filterQueryParam: false,
            maxConcurrentMetadataRequests: 1,
            servers: {
                dicomWeb: [
                    {
                        name: 'DCM4CHEE',
                        wadoUriRoot: 'https://dicomcloud.azurewebsites.net/api', /* https://dicomcloud.azurewebsites.net/api https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado /api/WadoQidoAPI  /api/WadoUriAPI/getImageDicom */
                        qidoRoot: 'https://dicomcloud.azurewebsites.net/api', /* https://dicomcloud.azurewebsites.net/api https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs /api/WadoQidoAPI */
                        wadoRoot: 'https://dicomcloud.azurewebsites.net/api', /* https://dicomcloud.azurewebsites.net/api https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs /api/WadoQidoAPI */
                        qidoSupportsIncludeField: true,
                        imageRendering: 'wadors', /* wadors / wadouri voir : https://github.com/OHIF/Viewers/issues/1338 et https://github.com/OHIF/Viewers/issues/482 */
                        thumbnailRendering: 'wadors', /* wadors / wadouri */
                        enableStudyLazyLoad: true,
                    },
                ],
            }
        },
        containerId,
        componentRenderedOrUpdatedCallback
    );
```
When pointing towards https://dicomcloud.azurewebsites.net/api (with the studyUID 1.2.840.86.755.86226839.811.1198516), I have the loading status of the current image updated correctly while the loading occurs (from the 0 to a 100%) : 

![LoadingStatusWorkingPointingDicomCloud](https://user-images.githubusercontent.com/37896804/91326420-9d7c5980-e7c4-11ea-998c-aa0d119c53eb.png)

When pointing towards https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs (with the studyUID 1.3.6.1.4.1.25403.345050719074.3824.20170126085406.1 for example), the loading status of the current image stays at 0% until the image is fully loaded : 

![LoadingStatusNotWorkingPointingDcm4chee](https://user-images.githubusercontent.com/37896804/91333020-4af36b00-e7cd-11ea-8265-6d65bb30fbe5.png)

**Comment by Zaid-Safadi** [comment]
That's interesting @sylvainb31, I am not sure why would that be if both are using wado-rs. Seems to be a good question to ask at the https://github.com/dcmjs-org/dcmjs/issues why the progress status doesn't change.

The good news it works well in DICOMcloud  :)
