### ISSUE TITLE
IIS Publish: Could not load file or assembly 'Dicom.Native' or one of its dependencies

### ISSUE THREAD

**Issue by marns** [DICOMcloud/DICOMcloud#107]
Debugging in Visual Studio with IIS Express is working correctly for me, but when trying to publish to IIS I get the following error in browser:

> Could not load file or assembly 'Dicom.Native' or one of its dependencies

Tried various configurations to specify x64 in project platforms; also tried enabling 32-bit applications in the app pool. Interestingly, when enabling 32-bit applications, the error becomes:

> Could not load file or assembly 'Dicom.Native64' or one of its dependencies

Any suggestions?

**Comment by Zaid-Safadi** [comment]
@marns Check the bin folder where you published, which Dicom.Native do you have? Or do you have both Dicom.Native and Dicom.Native64?

**Comment by marns** [comment]
@Zaid-Safadi both are in the bin folder

**Comment by Zaid-Safadi** [comment]
You can't have both 32 and 64 bit as the .NET framework will try to load both and one will always fail with either configuration, this is a .NET issue not related to DICOMcloud or fo-dicom

Delete the Dicom.Native64 and keep the config in IIS to 32-bit

**Comment by marns** [comment]
Got it working, thanks!
