### ISSUE TITLE
How to parse WadoRsResponse that encapsulating JPEG image data?

### ISSUE THREAD

**Issue by JiangWeian** [DICOMcloud/DICOMcloud#115]
The response received by the front end is a string:
![TIM图片20210206165832](https://user-images.githubusercontent.com/56569509/108646898-472d7080-74f2-11eb-93bd-035b2e21fa8e.png)

The first line is "--DICOM DATA BOUNDARY".How to convert image BLOB data, I want to download it with a element:
		   const blob = response; //new Blob([jpegText], {type:'image/jpeg'});
		   
		   const URLObj = window.URL || window.webkitURL;
		   const a = document.createElement('a');
		   const href = URLObj.createObjectURL(blob);
		   a.href = href;
		   a.download = filePrefix + 'image.jpg';
		   document.body.appendChild(a);
		   a.click();
           document.body.removeChild(a);
		   window.URL.revokeObjectURL(href);

**Comment by JiangWeian** [comment]
@Zaid-Safadi , The response received by the front end is a string:
![TIM图片20210206165832](https://user-images.githubusercontent.com/56569509/108646934-60ceb800-74f2-11eb-9e41-8c165cb5c639.png)

**Comment by Zaid-Safadi** [comment]
hey @JiangWeian , thanks for tagging!

You will need to parse this manually as this is how the DICOM specs require the data to be returned using a "multipart" return type.

You can try using some libraries for parsing multi-part responses, here is one option that might be worth looking at (I didn't try this lib):
https://github.com/freesoftwarefactory/parse-multipart#readme
