### ISSUE TITLE
There are two DICOM images generated jpg images are black

### ISSUE THREAD

**Issue by JiangWeian** [DICOMcloud/DICOMcloud#116]
@Zaid-Safadi 
The DICOM images are:
[DICOM.zip](https://github.com/DICOMcloud/DICOMcloud/files/6028153/DICOM.zip)

Display in viewer is normal:
![TIM图片20210223180747](https://user-images.githubusercontent.com/56569509/108828637-091f7200-7602-11eb-9879-75a0cab71d50.png)

In the code I call is :
        public static bool WriteTo(fo.DicomDataset dicomObject, int frame, string fileName)
        {
            var frameIndex = frame - 1;
            var dicomImage = new DicomImage(dicomObject, frameIndex);

                string directory = Path.GetDirectoryName(fileName);
                if(!Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                using (var bitmap = dicomImage.RenderImage(frameIndex).AsBitmap())
                using (FileStream stream = File.Open(fileName, FileMode.CreateNew))
                {
                    bitmap.Save(stream, System.Drawing.Imaging.ImageFormat.Jpeg);
                    //   stream.Position = 0;
                    stream.Flush();
                    stream.Close();
                }

            return success;
        }

**Comment by JiangWeian** [comment]
@Zaid-Safadi , fo-dicom version 3.0.2 has this bug:
https://github.com/fo-dicom/fo-dicom/issues/1158

I tested and found that version 4.0.2 only solved this problem at the beginning.
Will DICOMcloud upgrade the dependency of fo-dicom?

**Comment by Zaid-Safadi** [comment]
@JiangWeian thanks for reporting this and tracking it at the fo-dicom library. 

I have very limited time to focus on the DIOMcloud project but would welcome a PR with the upgraded fo-dicom version if that is something you are willing to contribute
