### ISSUE TITLE
Issues with DICOM SR in OHIF Basic Viewer 3.3

### ISSUE THREAD

**Issue by skovour** [DICOMcloud/DICOMcloud#138]
## Expected Behavior
On a locally built OHIF 3.3 integrated with Orthanc locally
1. Load a CT volume into basic viewer
2. Draw an annotation/measurement on a CT slice.  
3. Yes to track the measurements.  
4. Export report.  
5. Close the basic viewer
6. Try to load the same series again 

## Actual Behavior
At step 6 above viewer shows continuous loading

## Steps to Reproduce the Problem
See above.  Looks like saving DICOM SR into ORTHANC and loading back is an issue.
I tried to reproduce this problem on public server https://v3-demo.ohif.org/.   When I try to export Report (at step 4 above), I get an error.  It is not even saving to DICOM SR.

Please see screen shots.
![Issue2](https://user-images.githubusercontent.com/45807884/216481065-c36f2f07-88a2-4efd-ab5a-b4e66846245a.png)
![issue1](https://user-images.githubusercontent.com/45807884/216481069-45623e15-d2ce-4876-94f1-8c5a8b5e0cd9.png)
![console_error2](https://user-images.githubusercontent.com/45807884/216481070-3814358b-7de5-4fd1-833d-ebca4b889360.png)
![console_error1](https://user-images.githubusercontent.com/45807884/216481072-bb567233-fd40-47c3-a687-c34331b54841.png)

----------------------------  Update --------------------------------
After investigation, looks like this is a known issue.
I can see from the comments that when DICOM SR is stored none of the patient attributes are stored. See in attached screen shot (line 14395).   

So the stored SR is interpreted by Orthanc is different than OHIF.

a. Orthanc groups dicom instances by 1. Patient ID and Patient Name, 2. Group by Study instance ID, ..then series and so on.

b. Where as OHIF browser grouping them by study instance ID without checking patient level demographics with an assumption that study instance UID need to be unique (not a bad assumption)

So, the problem is when that particular SR series is loaded.  On OHIF request to load the study, Orthanc finds the same study instance UID associated with multiple patients and hence it returns the error.  OHIF not able to load that study anymore.  

If I can go to orthanc and deleted that an empty patient object associated with SR object, OHIF loads the study without SR and without any issue.  

I thought of fixing, but it is not clear how I can get patient demographic information in generateReport method.

If any one can help, I can submit pull request to fix the issue. 
![dcmjs es js](https://user-images.githubusercontent.com/45807884/216781310-8832d61f-6529-4f50-a443-8decda06f464.png)

**Comment by Zaid-Safadi** [comment]
@skovour  this DICOMcloud not Orthanc. You also should report this in OHIF
