### ISSUE TITLE
Instructions for Azure deployment?

### ISSUE THREAD

**Issue by tiloc** [DICOMcloud/DICOMcloud#21]
I am successfully running the DICOMcloud locally, but would like to install it into the Azure Cloud. I have located the azuredeploy.json, but it is pointing to non-existent URLs for resource download. I have also looked at the route through the Publish functionality from Visual Studio, but not sure which resources I need to setup in the cloud, especially how to properly get an Azure SQL instance properly configured with the required table structure.

Is there any documentation on the required steps for either route?

**Comment by tiloc** [comment]
I have also tried the Deploy to Azure button in your other account, but I am getting a message:
**There was an error loading the template from URI 'https://raw.githubusercontent.com/Zaid-Safadi/DICOMcloud/development/azuredeploy.json'. Ensure that the template is publicly accessible and does not have any comments.**

**Comment by Zaid-Safadi** [comment]
Hi @tiloc , thank you for reporting this. I'll include a documentation for the Azure deployment soon. Please let me know if you have specific things beside the SQL Database configuration that you like to focus on.

-Zaid AlSafadi

**Comment by Zaid-Safadi** [comment]
I've added a documentation section that explains how to create and deploy the database in Azure SQL (and MS SQL Server) here:

[https://dicomcloud.github.io/docs/dicomcloud/database-deploy/](https://dicomcloud.github.io/docs/dicomcloud/database-deploy/)

Does this help you @tiloc ?

**Comment by tiloc** [comment]
This looks like very helpful information. I haven't had the time yet to try these instructions to see where I have some gaps in my understanding. I will let you know once I had the time to try this.

**Comment by Zaid-Safadi** [comment]
anything further on this that I can help you with @tiloc?
