### ISSUE TITLE
QIDO: UID list parsing is not according to standard

### ISSUE THREAD

**Issue by hkoestin** [DICOMcloud/DICOMcloud#41]
## Expected Behavior
A list of UIDs (e.g. StudyInstanceUID) shall be separated with ',' in the URL and not with '\'.

From the standard: http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_6.7.html#sect_6.7.1.1.1

> Each {attributeID} query key shall be unique unless the associated DICOM Attribute allows UID List matching (see Section C.2.2.2.2 in PS3.4 ), in which case each {value} will be interpreted to be an element of the UID List.

The linked section http://dicom.nema.org/medical/dicom/current/output/chtml/part04/sect_C.2.2.2.2.html actually says, that the backslash (\) char shall be used, but this is for native DICOM only.

I did ask that question in the DICOM protocol group and got answered it now:
https://groups.google.com/forum/?hl=en#!topic/comp.protocols.dicom/NHA4l-q8Fo0

> The correct implementation is to use commas in QIDO-RS; the PS3.18 trumps the reference in Part 4. We will submit a CP to make this more clear in the coming weeks. 

## Actual Behavior
When passing in e.g. "?StudyInstanceUID=1.2.3,1.2.4", the service accepts but does not return correct things. 

## Steps to Reproduce the Problem
See above.

# Possible solution
One would need to add special handling for UI VR in the query service.

https://github.com/DICOMcloud/DICOMcloud/blob/cff2f160383d3da9204421be41d41b6ea7110a25/DICOMcloud.Wado/Services/QidoRsService.cs#L337

In case VR UI is passed an the value contains ",", then you would need to replace that value by a '\' char. That is a quite simple line of code to change.

Cheers, Harald

**Comment by Zaid-Safadi** [comment]
Thank you @hkoestin for pointing this out and the clear explanation. I've reviewed the sources and I see your point.

The solution you proposed should be the right place to handle this correctly. I'll put it on my road map for next version.

**Comment by Zaid-Safadi** [comment]
This is now fixed. Turned out there were a couple of other things needed to be fixed to support UID multi-value matching.

Thanks for reporting this @hkoestin
