### ISSUE TITLE
The first one of the sequence will be swapped with the middle image

### ISSUE THREAD

**Issue by q467725136** [DICOMcloud/DICOMcloud#46]
Hello, I found a bug. If you upload enough images of a sequence, the first one of the sequence will be swapped with the middle image. (If you upload 5 images, there is no problem. If you upload 8 images, you will have problems. )

I also tried to modify the code, but I got some trouble. I found that there is no problem when looking up the database.，The first one is 097.
![1](https://user-images.githubusercontent.com/42882876/54184864-9be0a800-44e2-11e9-8b4a-fd84a196b338.png)

The instance also is no problem，the first one is also 097.
![2](https://user-images.githubusercontent.com/42882876/54184922-bf0b5780-44e2-11e9-81de-5795e26752cd.png)

 but the actionContext takes 124 when it takes the first one (my The sequence is from 097-150, so the first one (097) is interchanged with the middle one (124))
![3](https://user-images.githubusercontent.com/42882876/54184935-c6326580-44e2-11e9-99ce-4d5745689ab9.png)

I hope you can help me：)

**Comment by Zaid-Safadi** [comment]
@q467725136 I am trying to follow the explanation but I still don't understand the problem.
Is t his a problem in the query or  the store? 
are the results being returned from the "Search" method not ordered as stored or is  there something else?

The sorting order is based on a different algorithm which is different for each query level. You can also change this behavior by implementing your sorting algorithm and plug it in the framework using the factory:
https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud.Wado.WebApi/App_Start/DICOMcloudBuilder.cs#L133

https://github.com/DICOMcloud/DICOMcloud/blob/master/DICOMcloud.DataAccess.Database/SortingStrategyFactory.cs

https://github.com/DICOMcloud/DICOMcloud/blob/master/DICOMcloud.DataAccess.Database/ObjectArchieveSortingStrategy.cs

If you are taking about something else, please send me an anonymized dataset with exact steps to reproduce.

**Comment by q467725136** [comment]
I found that sorting chaos may be related to the browser kernel version, I sorted differently in Google kernel 73 and 69 (69 is basically the same as 69 sorting, but not in normal order)

**Comment by Zaid-Safadi** [comment]
@q467725136 is this still an issue?
