### ISSUE TITLE
Wado-RS GetStudies not always working

### ISSUE THREAD

**Issue by shelbypereira** [DICOMcloud/DICOMcloud#55]
I am trying to test more deeply the WADO services.

I see that when I place a breakpoint in the GetStudies method below and when I use the url http://localhost:44301//wadors/studies/20
It works,  the breakpoint is hit!
This works also: http://localhost:44301//wadors/studies/20xasd

However if I use a URL with a dot

http://localhost:44301//wadors/studies/20.22
the breakpoint is not hit.  I also tested from the DICOMCloud test page and I see that the breakpoint is not hit.

I think in this case the Controlleris interpreting the dot part of page insted of treating the whole last part as the StudyInstanceUID

From the standard the letters , numbers AND the "."  should be supported.

Am I perhaps missing something or is there a simple fix since this is an important use case.  Most UIDs tend to have dots as the separator.

[Route("wadors/studies/{StudyInstanceUID}")]
        [HttpGet]
        public HttpResponseMessage GetStudies 
        ( 
            [ModelBinder(typeof(RsStudiesRequestModelBinder))] 
            IWadoRsStudiesRequest request 
        )
        {
            return WadoService.RetrieveStudy ( request ) ;
        }

I am currently examining: https://stackoverflow.com/questions/27872820/how-can-i-use-mvc5-attribute-based-routes-with-a-dot-period-in-them
And there seem to be some web.config solutions there.  I have tested adding the attribute to the modules tag as described in SO.
 <modules runAllManagedModulesForAllRequests="true">

It works.  They mention a possible performance penalty,  however it should be minor for typical use cases for this code since these are low traffice servers. (not serving 1000's of pages per second...)
I will submit a PR directly onto the 4.0 branch.

**Comment by Zaid-Safadi** [comment]
@shelbypereira, you are right. This is something that need to be handled in the server. In my tests, I was manually adding a slash at the end.

I like the second option of adding a trailing slash to the request. Do you have any thoughts about it?

**Comment by shelbypereira** [comment]
Hi I actually committed a fix to the 4.0 branch before your message. Yes Adding the slash is fine also.  My thought was the overhead by the web.config solution is negligible for applications which will use this code so the commit contains the web.config change which I tested (and fixes the issue).

**Comment by Zaid-Safadi** [comment]
This is fixed in b7ac27abb5443b06363c1ff660f8281fa390305d
