### ISSUE TITLE
Easiest way to clear the DicomCloud Webapi server DB and storage?

### ISSUE THREAD

**Issue by shelbypereira** [DICOMcloud/DICOMcloud#56]
I am testing the DICOMwebjs demo, and I am wondering if there is an easy way to clear the DB and all images stored in the DICOMCloud server?

**Comment by Zaid-Safadi** [comment]
yes, @shelbypereira these two app keys should help:
```
    <add key="app:PacsStorageConnection" value="|DataDirectory|\App_Data\Storage\ds" />
    <add key="app:PacsDataArchieve" value="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DB\DICOMcloud.mdf;Initial Catalog=DICOMcloud;Integrated Security=True" />
```

Update the "app:PacsStorageConnection" with something you can easily locate and delete (e.g. C:\dicomServer)

The "app:PacsDataArchieve" is attaching a local database which from a directory that gets overwritten from a template database when you "re-build" the WebAPI project, check the project build events:
xcopy "$(ProjectDir)../Resources\Database\DICOMcloud.mdf" "$(ProjectDir)App_Data\DB\*" /d /y
xcopy "$(ProjectDir)../Resources\Database\DICOMcloud.ldf" "$(ProjectDir)App_Data\DB\*" /d /y
