### ISSUE TITLE
Can we connect this with exisiting PACS

### ISSUE THREAD

**Issue by mbilalsh** [DICOMcloud/DICOMcloud#58]
Can we connect with exisiting PACS? 
I have Rogan Delft PACS, it is a 10 years older version, in which dicomweb protocol is not supported.

**Comment by Zaid-Safadi** [comment]
@mbilalsh  I am not familiar with Rogan but you can write connector that talks directly with the database. It will require some work to understand the DB of the server you have but should be doable

What kind of DB does Rogan Delft has?

**Comment by mbilalsh** [comment]
it is SQL Server, i can send you db schema script. but cant share publicly.

**Comment by Zaid-Safadi** [comment]
@mbilalsh  you can send the schema with more detail here if you don't want to share publicly: support@zeuscloudimaging.com

**Comment by mbilalsh** [comment]
i have sent you email
