### ISSUE TITLE
Issue with the base URL of DICOMWeb RESTful services

### ISSUE THREAD

**Issue by nroduit** [DICOMcloud/DICOMcloud#59]
DICOMcloud's RESTful APIs are divided into 3 sub-services:
* /qidors/* (GET)
* /wadors/* (GET)
* /stowrs/* (POST)

The DICOM standard has evolved and now RESTfull services are grouped together, see http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_7.2.html and http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.3.html

So the URL for QIDO-RS, WADO-RS and STOW-RS must have the same base URL, e.g.
* QIDO-RS: http://localhost/dicomweb/studies?PatientName=Test
* WADO-RS: http://localhost/dicomweb/studies/1.3.6.1.4.1.11129.5.5.18430169333457801

**Comment by Zaid-Safadi** [comment]
@nroduit I am glad the standard has been updated to treat these resources as a true REST API.
I'll add this to the pipeline of items to be included next

**Comment by Zaid-Safadi** [comment]
DICOMcloud is updated to share the same base URL.
Here is the updated swagger: http://dicomcloud.azurewebsites.net/swagger/

The old URLs are also still supported, so these two are the same:
http://dicomcloud.azurewebsites.net/qidors/studies
http://dicomcloud.azurewebsites.net/api/studies

Thanks @nroduit for pointing the update to the standard.

**Comment by CameronGo** [comment]
@Zaid-Safadi it looks like the URL referenced above no longer functions?
