### ISSUE TITLE
Find a bug. If access Qido interface with URL http://localhost:44301/qidors/studies/1.3.12.2.1107.5.3.4.2373.1.20171103124622/series

### ISSUE THREAD

**Issue by JiangWeian** [DICOMcloud/DICOMcloud#60]
If you directly use the URL(ex: http://localhost:44301/qidors/studies/1.3.12.2.1107.5.3.4.2373.1.20171103124622/series) to access the Qido interface, you will get a 404 page. This is because the QidoRequestModelConverter object cannot find the uid information when parsing the URL.
For solving this problem, we need to make the following changes to the code:
- In class QidoRequestModelConverter, add a method CheckAndFillUids()
private void CheckAndFillUids(IValueProvider valueProvider, IQidoRequestModel wadoReq)
        {
            string strStudyInstanceUid = fo.DicomTag.StudyInstanceUID.DictionaryEntry.Keyword;
            string strSeriesInstanceUid = fo.DicomTag.SeriesInstanceUID.DictionaryEntry.Keyword;
            string strSopInstanceUid = fo.DicomTag.SOPInstanceUID.DictionaryEntry.Keyword;

            if (!wadoReq.Query.MatchingElements.ContainsKey(strStudyInstanceUid))
            {
                ValueProviderResult valueResult = valueProvider.GetValue(strStudyInstanceUid);
                if (valueResult != null)
                {
                    string studyInstanceUid = valueResult.RawValue as string;
                    if (!string.IsNullOrEmpty(studyInstanceUid))
                        wadoReq.Query.MatchingElements.Add(strStudyInstanceUid, studyInstanceUid);
                }
            }

            if (!wadoReq.Query.MatchingElements.ContainsKey(strSeriesInstanceUid))
            {
                ValueProviderResult valueResult = valueProvider.GetValue(strSeriesInstanceUid);
                if (valueResult != null)
                {
                    string seriesInstanceUid = valueResult.RawValue as string;
                    if (!string.IsNullOrEmpty(seriesInstanceUid))
                        wadoReq.Query.MatchingElements.Add(strSeriesInstanceUid, seriesInstanceUid);
                }
            }

            if (!wadoReq.Query.MatchingElements.ContainsKey(strSopInstanceUid))
            {
                ValueProviderResult valueResult = valueProvider.GetValue(strSopInstanceUid);
                if (valueResult != null)
                {
                    string sopInstanceUid = valueResult.RawValue as string;
                    if (!string.IsNullOrEmpty(sopInstanceUid))
                        wadoReq.Query.MatchingElements.Add(strSopInstanceUid, sopInstanceUid);
                }
            }
        }

and call CheckAndFillUids() in this class's method TryParse(),
            CheckAndFillUids(bindingContext.ValueProvider, wadoReq);
            result = wadoReq;
- In class QidoRequestModelBinder's method BindModel(), parmeter 'bindingContext'  should pass in when calling TryParse(),
  if ( new QidoRequestModelConverter ( ).TryParse ( actionContext.Request, bindingContext, out result) )

### Hope you will take my advice.

**Comment by Zaid-Safadi** [comment]
Hi @JiangWeian thanks for reporting this and submitting the code. Can you please create PR with this change and I'll be happy to review it and include it.

**Comment by JiangWeian** [comment]
OK, @Zaid-Safadi, I have pull request with branches  JiangWeian-patch-1-1

**Comment by Zaid-Safadi** [comment]
Thanks @JiangWeian, I've merged your changes to development with a quick test and looks good. 

Can you please verify form your end and confirm the bug is fixed?
