### ISSUE TITLE
Excuse me, how can DICOMcloud load the DICOM of another server in batch?

### ISSUE THREAD

**Issue by luohao110** [DICOMcloud/DICOMcloud#66]
Whether it is possible to query the information of another server: query all Studies, or query results through StudiesId, and store them in DICOMcloud.
What am I supposed to do?

**Comment by Zaid-Safadi** [comment]
Hi @luohao110, you will need to query the images and retrieve them from the other server outside of the DICOMcloud then you can store them in batches using the STOW-rs service
