### ISSUE TITLE
sometimes using STOW-RS throws an exception internally in the fo-dicom library

### ISSUE THREAD

**Issue by shelbypereira** [DICOMcloud/DICOMcloud#67]
a couple of months ago I helped migrate the code to use fo-dicom 4.x

I just saw an issue today which I think is linked to the migration
When constructing the WadoResponse  in the file WadoStoreResponse.cs, the following is call is made.

However the original line 
       var classUID = ds.GetSingleValueOrDefault<DicomElement> ( DicomTag.SOPClassUID, null ) ;
sometimes throws an exception
when I changed the type to <string> it works always.
also note the corresponding changes at the bottom:   ===>         dataset.AddOrUpdate(   DicomTag.SOPClassUID   ,classUID ) ;

I would normally make a PR, but my code base has diverged significantly since I am trying to use .NET CORE 3.0
 

``` cs
private DicomDataset GetReferencedInstsance(DicomDataset ds)
{
    var classUID = ds.GetSingleValueOrDefault<DicomElement>(DicomTag.SOPClassUID, null);
    var sopUID = ds.GetSingleValueOrDefault<DicomElement>(DicomTag.SOPInstanceUID, null);
    /* NOTE THE CHANGES DicomElement=> string */
    var classUID = ds.GetSingleValueOrDefault<string>(DicomTag.SOPClassUID, null);
    var sopUID = ds.GetSingleValueOrDefault<string>(DicomTag.SOPInstanceUID, null);
    var dataset = new DicomDataset();


    dataset.AddOrUpdate(classUID);
    dataset.AddOrUpdate(sopUID);
    /* NOTE THE  CORRESPONDING CHANGES  */
    dataset.AddOrUpdate(DicomTag.SOPClassUID, classUID);
    dataset.AddOrUpdate(DicomTag.SOPInstanceUID, sopUID);
    return dataset;
}
 
```

**Comment by Zaid-Safadi** [comment]
Hey @shelbypereira , I am unable to see the change here:
`var classUID = ds.GetSingleValueOrDefault ( DicomTag.SOPClassUID, null ) ;`

What is the error that you are getting and how do you suggest changing this?

on a side note, will you be willing to share your .NET Core version of the code and add it to the Org. Repo?

**Comment by shelbypereira** [comment]
sorry I copied the code incorrectly.  Here is the original function as it is currently in github
private DicomDataset GetReferencedInstsance ( DicomDataset ds )
        {
            var classUID = ds.GetSingleValueOrDefault<DicomElement> ( DicomTag.SOPClassUID, null ) ;
            var sopUID   = ds.GetSingleValueOrDefault<DicomElement> ( DicomTag.SOPInstanceUID, null ) ;
            var dataset  = new DicomDataset ( ) { AutoValidate = false };

            dataset.AddOrUpdate ( classUID ) ;
            dataset.AddOrUpdate ( sopUID ) ;

            return dataset ;
        }

so basically  I removed <DicomElement>   to force it to a string,

The exception was in fo-dicom  I no longer have the original exception since I have moved on,  but the library was unable to convert the type.  I had actually found similar issues in github for fo-dicom which helped me find the solution.

I would normally be appy to share the code, but in fact I have stripped out most of it, since I use only a small part.  Additionally the code is now tightly integrated into our solution is is no longer DICOMCloud only.

I am happy to share any bug fixes I find and continue to scan the repository if there are other issues.

**Comment by Zaid-Safadi** [comment]
@shelbypereira I was able to see an issue with the original code where fo-dicom returns null for the values of the "SOP Class UID" and "SOP Instance UID" instead of the element. 
This wasn't throwing an exception but simply it was causing the response dataset not to be updated with the results.
