### ISSUE TITLE
Questions on testing:

### ISSUE THREAD

**Issue by shelbypereira** [DICOMcloud/DICOMcloud#68]
I am testing Dicomcloud in various scenarios I have a few questions:

1.  I see there is support for transformations  :  did you have any guidance for testing,  do you have some test data (images) which can be added to the repository to do some standard tests on the transformations.

2.  I see that the media types supported are application/dicom, dicom+xml, xml, jpg.  Again do you have some suggestions how to test these, do you have some test dicom files with the media type supported?

3. Similarly  I see there is support fo /Metadata,  actually I don't know much about this,  can you comment on how this is used, how I can test and if there is some test data that can be added?

**Comment by Zaid-Safadi** [comment]
Hi @shelbypereira , I'll try to answer to the best of my understanding:

> 1. I see there is support for transformations : did you have any guidance for testing, do you have some test data (images) which can be added to the repository to do some standard tests on the transformations.

What transformation do you mean? JSON <--> XML or TransferSyntax? 
JSON <--> There is a unit tests with sample data in the project repo that you can check [here](https://github.com/DICOMcloud/DICOMcloud/blob/development/UnitTests/DICOMcloud.Dicom.UnitTest/DicomDatasetConvertersTests.cs)

For TransferSyntax transformation, I'm using the [DICOMweb-js](https://github.com/dicomcloud/dicomweb-JS) project to test

In fact, most of the functionalities of DICOMcloud can be tested live in the DICOMweb example:
http://dicomweb.azurewebsites.net/

You can load an image in the viewer tab, then select a transfer syntax from the dropdown

![image](https://user-images.githubusercontent.com/10813109/72221718-1e832b00-352b-11ea-900a-d650b37e64a5.png)

> 2. I see that the media types supported are application/dicom, dicom+xml, xml, jpg. Again do you have some suggestions how to test these, do you have some test dicom files with the media type supported?


Same as the above, you can use the DICOMweb-js live to test some of these. However, you might need to write your own test. For example to get a DICOM image in jpeg from DICOMcloud, you can use WADO-URL with content type "image/jpeg", 
Here is an example for JPEG (this will open the DICOM image in the browser)
https://dicomcloud.azurewebsites.net/wadouri?RequestType=wado&studyUID=1.2.392.200036.9110.7837194123.2.20121014084047&seriesUID=1.2.392.200036.9110.7837194123.3.3.20121014084141&objectUID=1.2.392.200036.9110.7837194123.1.1.20121014084141.0&contentType=image/jpeg

3. Similarly I see there is support fo /Metadata, actually I don't know much about this, can you comment on how this is used, how I can test and if there is some test data that can be added?

Also you can use the DICOMweb-js demo:
![image](https://user-images.githubusercontent.com/10813109/72221694-f09de680-352a-11ea-91fd-2a2d0a25dfd7.png)

**Comment by shelbypereira** [comment]
Thanks for your detailed reply and answers, very helpful!  I will use the online tool as you suggest, this is very useful.
