### ISSUE TITLE
Question/bug ? concerning the QidoRS creationOfElement or sequence

### ISSUE THREAD

**Issue by shelbypereira** [DICOMcloud/DICOMcloud#70]
The QidoRsService contains the following code:

 static void CreateSequence(List<string> elements, int currentElementIndex, DicomDataset dicomRequest, string value)
        {
            uint tag = GetTagValue ( elements[currentElementIndex] ) ;
            var dicEntry = DicomDictionary.Default[tag] ;
            DicomSequence sequence ;
            DicomDataset  item ;
            
            dicomRequest.AddOrUpdate ( new DicomSequence ( dicEntry.Tag ) ) ;
            sequence = dicomRequest.GetSingleValue<DicomSequence>(dicEntry.Tag);

....

The call to GetSingleValue is always throwing an exception:
Dicom.DicomDataException : DicomTag doesn't support values.
   at Dicom.DicomDataset.GetSingleValue[T](DicomTag tag)
   at DICOMcloud.Wado.QidoRsService.CreateSequence(List`1 elements, Int32 currentElementIndex, DicomDataset dicomRequest, String value) i

The exception seems to make sense since we should not use GetSingleValue to get a Sequence

I think GetSequence needs to be used here.  Perhaps it was working in the past with an older version of fo-dicom?

**Comment by Zaid-Safadi** [comment]
@shelbypereira thanks for reporting. I was able to reproduce and fix this in the latest code.
Also added a unit test for this case.
