### ISSUE TITLE
Artifacts in Picture with OHIF Viewer.

### ISSUE THREAD

**Issue by nutzlastfan** [DICOMcloud/DICOMcloud#73]
Hi,

i am using ohif with studylist (not the standalone viewer) and dicomcloud. (wich is a really great project !) I had to make some small modifiactions so it matches our file and DB structure.

After opening an entry from the resultset the viewer starts, loads the metadata for the the series:
qidors/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}/metadata

`protected virtual HttpResponseMessage ProcessJsonMetaDataRequest(IWadoRequestHeader header, IObjectId objectID)
        {
            HttpResponseMessage response = new HttpResponseMessage();
            StringBuilder jsonReturn = new StringBuilder("[");
            JsonDicomConverter converter = new JsonDicomConverter() { IncludeEmptyElements = true};
     ...
System.Data.DataTable tempdb = DataAccess.DB.get_datatable("", "", "..", "..", sqlstr );
            if (tempdb.Rows.Count > 0)  {
                foreach (System.Data.DataRow dr in tempdb.Rows)  {
               string filename = "..." +  dr[0].ToString();
                fo.DicomFile defaultFile;
                defaultFile = fo.DicomFile.Open(filename, fo.FileReadOption.SkipLargeTags);
                     if (jsonReturn.Length > 1) {    jsonReturn.Append(","); }
                     jsonReturn.AppendLine(converter.Convert(defaultFile.Dataset));
                    jsonReturn.Remove(jsonReturn.Length - 3, 3);
                    jsonReturn.AppendLine((", '7FE00010':{ 'vr':'OW','BulkDataURI': 'http://.../wadors/studies/" + defaultFile.Dataset.GetString(Dicom.DicomTag.StudyInstanceUID) + "/series/" + defaultFile.Dataset.GetString(Dicom.DicomTag.SeriesInstanceUID) + "/instances/" + defaultFile.Dataset.GetString(Dicom.DicomTag.SOPInstanceUID) + "' } }").Replace("'", "\""));
                    defaultFile = null;  }  }
            jsonReturn.Append("]");
            tempdb.Dispose();
            response = new HttpResponseMessage(System.Net.HttpStatusCode.OK);
           response.Content = new StringContent(jsonReturn.ToString(),Encoding.UTF8,MimeMediaTypes.Json);
    return response;`

and then tries to retrive the 0 index frame per dicom instance

wadors/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}/instances/{SOPInstanceUID}/frames/{FrameList}

## Expected Behavior

From what i have gatherd only the pixeldata/or frame should be returned with the corresponding mime type.

## Actual Behavior
![dicomexpl_full](https://user-images.githubusercontent.com/25078990/73053621-79e8dd80-3e88-11ea-9799-bd491f42f58f.jpg)

LocalStorageLocation.GetReadStream returns the full dicom file. And the ohif viewer displays it with artifactes.

I'am not shure if this is self inflicted because of the changes i made regarding the storage and db.

I hope someone can help me.

**Comment by Zaid-Safadi** [comment]
Hey @nutzlastfan I am still not clear of what the problem you are describing is, but the behavior of querying the metadata first then retrieving the individual "instances" works as expected. 

I will need more information about your setup and configuration to be able to help. 

What OHIF version are you using (v1 Meteor or v2 React)? 
Are you using wado-uri to retrieve the images in OHIF or wado-rs?

Does the problem you are having happens with all images or specific ones? 

Also noticed the snapshot you have has the thumbnail vertically while the image orientation on the viewport horizontal, did you perform a rotate on the viewport or something else is off here?

**Comment by nutzlastfan** [comment]
I am using the react based version (current version from github).
The Viewer uses wado-rs, wadors/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}/instances/{SOPInstanceUID}/frames/{FrameList} to retrive the image.

No rotation or any image manipulation was done beforehand.

The problem exists with all images, the one in the screenshot is actually one of the better ones, 
the others are only artifacts. 

The Viewer seems to expect only the image data from the dicom file, when opening an instance on the ohif demo page the dcm4che backend return this: 

--5a297b56-d1cb-4f05-ac3e-5c1cbd60ec87
Content-Location: http://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.25403.345050719074.3824.20170125113417.1/series/1.3.6.1.4.1.25403.345050719074.3824.20170125113514.6/instances/1.3.6.1.4.1.25403.345050719074.3824.20170125113522.7/frames/1
Content-ID: <26df8046-80e6-483c-b4e2-14cf6d4fd70d@resteasy-multipart>
Content-Type: application/octet-stream

followed by what looks like image data but with little no none metadata, while dicomcloud currently at least in my version returns the whole dicom file as-is.

**Comment by Zaid-Safadi** [comment]
Hey @nutzlastfan if DICOMcloud is returning the whole dicom file as-is then you probably have messed up something in the `ObjectRetrieveService`

I've ran the viewer against DICOMcloud in wado-rs mode and it works fine returning only the extracted image data.

What you want to know about DICOMcloud is that it implements a caching mechanism by pre-generating the files with the image data only (among other things like json metadata, xml metadata, jpg...) to speed the retrieval of over the web.

It stores this using a strategy that doesn't require querying the database to get the location of the generated files but rather depends on the file hierarchy to locate the right file. I believe the top of this hierarchy is the **mime type and transfer syntax** 

My guess, is when you updated the code of DICOMcloud to match your directory structure, you didn't account for this and you are always returning the actual DICOM file.

Finally, if you don't want to pre-generate the image data, json, xml... that should be OK as DICOMcloud will generate on-demand (in-memory) if it doesn't find the files generated. Just make sure that you are only returning the DICOM file when the mime-type is `application/dicom`
``` cs
    public abstract class MimeMediaTypes
    {
        private MimeMediaTypes() { }

        public const string DICOM = "application/dicom";
```

Debug your code in the method below and see what files you are returning (notice the media type and transfer syntax in the locals window)

![image](https://user-images.githubusercontent.com/10813109/73148710-b8021f00-408b-11ea-902b-003c138634bd.png)

**Comment by nutzlastfan** [comment]
Thank you, it works. I haven't used the upload yet so I wasn't aware that it preprocesses everything.
I used the UncompressedPixelDataWrapper from the upload  function in getstream.
You can close the issue.

Thank you for your help.

**Comment by wangning08115** [comment]
@nutzlastfan   Hi, i am using https://github.com/OHIF/Viewers  too.
And when i upload a Dicom file to DICOMcloud, and  use OHIF/Viewers to view the Dicom file.
Then no image to display , And i find the DICOMcloud api return data is not same to http://server.dcmjs.org/dcm4chee-arc  server api.  
Can you help me , Give me what you change of project DICOMcloud?

**Comment by dannyrb** [comment]
@wangning08115, can you please create a new issue and the minimal steps required to reproduce the behavior you're experiencing (as well as detailing the behavior you expect)?
