### ISSUE TITLE
Possibility to load individual series or instances with ohif standalone viewer

### ISSUE THREAD

**Issue by nutzlastfan** [DICOMcloud/DICOMcloud#75]
## Expected Behavior
I am using the standalone ohif viewer in a desktop wpf app with multiple chromium-based windows hosting the ohif viewer. The windows accept drag and drop from the image browser in the wpf main window. When an object (study, series, image) is dropped an address change event is triggered and the navigation loads the corresponding data. Via viewer?ohif/study/{studyUid}/series

## Actual Behavior
For loading only specific instances or series thr necessary routes aren't jet implemented.
ohif/study/{studyUid}/series/{seriesUid}/instances/{sopUid}/frames

I added the options under that pull request:
https://github.com/DICOMcloud/DICOMcloud/pull/74

**Comment by Zaid-Safadi** [comment]
merged e66ee40c33ab5765085fbe4a3cd90723f45f094d
