### ISSUE TITLE
The "api" route for the Store service (STOW-RS) doesn't work without a Study Instance UID

### ISSUE THREAD

**Issue by Zaid-Safadi** [DICOMcloud/DICOMcloud#79]
## Expected Behavior
Calling the STOW-RS with the new api route without a studyInstanceUID parameter should be successful.
`https://dicomcloud.azurewebsites.net/api/studies/`
 

## Actual Behavior

```
Request URL: https://dicomcloud.azurewebsites.net/api/studies/
Request Method: POST
Status Code: 405 Method Not Allowed
Remote Address: 13.68.29.136:443
```

## Steps to Reproduce the Problem

  1. Call the STOW-RS endpoint using the unified URL "api" without specifying a studyInstanceUID

**Comment by Zaid-Safadi** [comment]
fixed

**Comment by nutzlastfan** [comment]
Just a general question should the save measurement function from ohif viewer work againts dicomcloud ?
