### ISSUE TITLE
Problem with decimal conversion on non different culture settings (german)

### ISSUE THREAD

**Issue by nutzlastfan** [DICOMcloud/DICOMcloud#81]
With the current release conversion of dicom values which have decimals in them can fail when non-english culture settings are enabled.
So in my case when converting a decimal value a dot would be changed to a comma which in return would be stripped when parsing.
It becomes noticeable when your trying to make measurements with the viewer (wrong scale, or particularly when reconstructing a ct with mpr.

The necessary fixes are primarily in the JsonDicomConverter.cs and XmlDicomConverter.cs
When parsing values with the  System.Globalization.CultureInfo.InvariantCulture  parameter, local  user settings which would affect the conversion are ignored.

See pull request #77

**Comment by Zaid-Safadi** [comment]
@nutzlastfan thanks for reporting and the PR.  I've cherry picked the commits from the JSON converter and squash merged into dev. bf2afd5dc51f6e3ed02b2ad1a2ecb2522dadbc34

I didn't see a fix for the XML converter that address this issue, the XML commits seems to address the encoding problem. I could be wrong but the commits don't have a descriptive message so I can't tell. Please consider providing a descriptive message with each commit.

**Comment by nutzlastfan** [comment]
The XML converter doesn't seem to have an issue with decimals.
I added the second issue for the character problem and made a new pull request. The last commits should now hopefully have a final commit description.

**Comment by Zaid-Safadi** [comment]
This is merged now. Thanks!
