### ISSUE TITLE
Problem when handling dicomdata with non english characters.

### ISSUE THREAD

**Issue by nutzlastfan** [DICOMcloud/DICOMcloud#84]
By default non-english characters would be changed when added to the dicom dataset object.

see pullrequest #83 

I added encoding parameters to the dataset.add functions when handling string values, so that non-english characters (german umlaute) wouldn't be changed on being added to the dicom dataset.
And I change the default encoding for the return string to utf8 in the convert function of the xmlconverter.

**Comment by Zaid-Safadi** [comment]
Thanks @nutzlastfan , I've also added some updates and merged your changes.
