### ISSUE TITLE
How to use swagger ?

### ISSUE THREAD

**Issue by wangning08115** [DICOMcloud/DICOMcloud#87]
I know dicomcloud use swagger doc for api.
But i don't know how to edit and generate file /swagger/swagger-restful.json

I guss this file has a  editor and edit it easy.
Can you help me？

**Comment by dannyrb** [comment]
Swagger.io has an editor: https://editor.swagger.io/

This project doesn't use it, but it might be nice to tie in Swashbuckle to generate this stuff automagically:

- https://github.com/domaindrivendev/Swashbuckle
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by Zaid-Safadi** [comment]
@wangning08115 this is the JSON file that you need to edit to update the swagger file:
https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud.Wado.WebApi/swagger/swagger.json

Back when I wrote this I did it manually but I bet there are better ways to generate it now.
