### ISSUE TITLE
FailedSOPSequence in dicom upload

### ISSUE THREAD

**Issue by OdungaTM** [DICOMcloud/DICOMcloud#93]
Files are being stored in the storage data archive but  no data is saved  in the database. Connection string works perfectly. Response  from server is FailedSOPSequence (0008,1197)with code 272. What could i be missing.

**Comment by Zaid-Safadi** [comment]
@OdungaTM this means there is an issue with the data in your DICOM dataset (missing required elements, invalid data...) causing the insert to DB operation to fail.

Did you look at the trace logs or exception being thrown?

**Comment by Zaid-Safadi** [comment]
@OdungaTM I believe this is now fixed in "Server fails to store when a DICOM file is invalid (valu doesn't confirm to VR) #99"
Can you verify?

**Comment by Zaid-Safadi** [comment]
closed as potentially fixed in #99
